version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: redhat123
      MYSQL_DATABASE: ogtest
      MYSQL_USER: admin
      MYSQL_PASSWORD: redhat123
    networks:
      - app-network
    ports:
      - "3306:3306"
  web:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: redhat123
    depends_on:
      - db
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "8080:80"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
